# Site settings
title: This Has to Work
email: your-email@domain.com
description: >>>> no words # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/ExData_Plotting1" # the subpath of your site, e.g. /blog/
url: "http://mamafanfan.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mamafanfan

# Build settings
markdown: kramdown
